select 
DATEOFBUSINESS as Businessday,
MMX_STORENUMBER AS store,  
MDA_OPENDATE "Opened MDA first of month",
MDAY0Y1 as "PERIMETRE",
ID_CHANNEL_NIV1 as SERVICETYPEMMX,
SUM(Y0REVENUE_HT) AS Revenue, 
SUM(CASE
        WHEN MDAY0Y1 = 'MDA' THEN Y0REVENUE_HT
        ELSE 0
    END) AS "Revenue MDA", 
SUM(Y2REVENUE_HT) AS "Revenue MDA 2PY", 
SUM(Y0NBINVOICES) AS Transaction, 
SUM(CASE
        WHEN MDAY0Y1 = 'MDA' THEN Y0NBINVOICES
        ELSE 0
    END) AS "Transaction MDA", 
SUM(Y1REVENUE_HT) AS "Revenue PY", 
SUM(CASE
        WHEN MDAY0Y1 = 'MDA' THEN Y1REVENUE_HT
        ELSE 0
 END) AS "Revenue MDA PY", 
    
SUM(Y1NBINVOICES) AS "Transaction PY",
SUM(CASE
        WHEN MDAY0Y1 = 'MDA' THEN Y1NBINVOICES
        ELSE 0
    END) AS "Transaction MDA PY",
SUM( Y1NBINVOICES) AS "Transaction MDA 2PY" 
from 
KFC_FRANCE_DW_PROD.DWH.SF_DSFI016_U3_SSSG_MMX_AMREST_DOM_DAY_STORE_CHANNEL_HOUR_V01
group by  
DATEOFBUSINESS,
MMX_STORENUMBER ,
MDA_OPENDATE ,
MDAY0Y1,
ID_CHANNEL_NIV1